version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Adjust version as needed
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install --save-dev mocha-junit-reporter  # Install JUnit reporter for Mocha

  pre_build:
    commands:
      - echo Setting up test environment...

  build:
    commands:
      - echo Running tests...
      - mkdir -p ./test-reports
      - npx mocha --reporter mocha-junit-reporter --reporter-options mochaFile=./test-reports/test-results.xml

  post_build:
    commands:
      - echo "Tests and coverage report completed on `date`"
      - ls -la ./test-reports

reports:
  test_reports:
    files:
      - test-results.xml
    base-directory: ./test-reports
    file-format: JUNITXML

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'node_modules/**/*'
