version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Setting up test environment...
      - mkdir -p ./test-reports

  build:
    commands:
      - echo Running tests...
      - npm test

  post_build:
    commands:
      - echo Tests completed on 'date'
      - echo Test results
      - ls -la ./test-reports || echo "No test reports found"

reports:
  test-reports:
    files:
      - "test-results.xml"
    base-directory: "./test-reports"
    file-format: "JUNITXML"

artifacts:
  files:
    - package.json
    - package-lock.json
    - "src/**/*"
    - "test/**/*"
    - "test-reports/**/*"
  base-directory: "."

cache:
  paths:
    - 'node_modules/**/*'
