# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g mocha-junit-reporter mocha-multi-reporters
      - npm install
      - mkdir -p ./test-reports
  build:
    commands:
      - echo Running Tests
      - npm test
      - npx mocha --reporter-options configFile=reporter-config.json "**/*.js"
      
  post_build:
    commands:
      - echo Tests Complete
      - echo Test Report Generated at $(date)
      - ls -la ./test-reports
reports:
  mocha-reports:
    files:
      - "test-results.xml"
    base-directory: "./test-reports"
    file-format: "JUNITXML"

artifacts:
  files:
    - package.json
    - package-lock.json
    - appspec.yml
    - "**/*"
  base-directory: "."
  secondary-artifacts:
    test_reports:
      files:
        - "test-results.xml"
        - "**/*.xml"
      base-directory: "./test-reports"
